### PR TITLE
Add api_key parameter in all requests

### LINKED ISSUE #92: HTTP 401 error when adding movies during signup locally in dev env
p1

- I have tested this and below is a quick fix,
  - We need to add params when searching movies with tmdb API
  ```
        const { data } = await axios.get(url, {
            params: {
                api_key: TMDB_TOKEN,
                query: query,
            },
            headers: {
                accept: "application/json",
                Authorization: `Bearer ${TMDB_TOKEN}`,
            },
        })
```

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
closes #92

### CODE REVIEW

**Review by AshuKr22 — APPROVED** [review]
works 👍

**Comment by mehul-m-prajapati** [comment]
@AshuKr22 : Please add labels in this one.

**Comment by hemanthkumar-21** [comment]
@AshuKr22  you can give level2 for this not level 3 @MastanSayyad

**Comment by AshuKr22** [comment]
@MastanSayyad  @Hemu21 while the changes seem small, it was a major bug in our application and no contributor was able to locally run the app. so finding this issue itself was a big task. So I will suggest it remains level 3. the lines of code do not justify the scale of problem this pr solved.

**Comment by hemanthkumar-21** [comment]
@AshuKr22  yes, but we are mentioning on few prs only as we are considering all the prs of the contributor. and if some where we left few level3 and for some where we mentioning. to make it fair and balance. As we don't want to discourage contributors. I hope you understand. It is based on the all the prs. I hope you understand. and @mehul-m-prajapati  is really doing great. But we have to follow some guidelines as it is a program. we doesn't made this pr as level1 we just made it level2. I hope you understand.

**Pull request merged**
