### PR TITLE
Add Delete list functionality to the lists

### LINKED ISSUE #203: Delete list

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #203 
https://github.com/user-attachments/assets/df14f620-de0a-4eff-8263-559ce0c04c04
hey @AshuKr22 please refer to this video 
Screenshot 2024-10-21 at 4 03 45 AM

### CODE REVIEW

**Comment by sid0000007** [comment]
@shubhagarwal1 , your solution is working fine. But We wanted to inform you that the user's Top 5 movies List cannot be deleted and also the favourite and watchlist list also (you can consider them as default one must have ). can you come up with a solution for this?

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 , your solution is working fine. But We wanted to inform you that the user's Top 5 movies List cannot be deleted and also the favourite and watchlist list also (you can consider them as default one must have ). can you come up with a solution for this?

When a user tries to delete these lists, we can display an error message or feedback to the user, and further handle the validation at the frontend and backend so that these lists could not be deleted optionally we can just remove the
trash icon from this lists by applying frontend validations

**Comment by sid0000007** [comment]
> > @shubhagarwal1 , your solution is working fine. But We wanted to inform you that the user's Top 5 movies List cannot be deleted and also the favourite and watchlist list also (you can consider them as default one must have ). can you come up with a solution for this?
> 
> When a user tries to delete these lists, we can display an error message or feedback to the user, and further handle the validation at the frontend and backend so that these lists could not be deleted optionally we can just remove the trash icon from this lists by applying frontend validations

frontend validation will be a good solution as of now. We can proceed with it.

**Comment by shubhagarwal1** [comment]
> > > @shubhagarwal1 , your solution is working fine. But We wanted to inform you that the user's Top 5 movies List cannot be deleted and also the favourite and watchlist list also (you can consider them as default one must have ). can you come up with a solution for this?
> > 
> > 
> > When a user tries to delete these lists, we can display an error message or feedback to the user, and further handle the validation at the frontend and backend so that these lists could not be deleted optionally we can just remove the trash icon from this lists by applying frontend validations
> 
> frontend validation will be a good solution as of now. We can proceed with it.

okay will implement this and finalise the PR

**Comment by shubhagarwal1** [comment]
hey @sid0000007 i have impoved the code so tha top 5 movies could not be deleted
Screenshot 2024-10-21 at 4 03 45 AM
as there is no trash icon on the list

**Review by AshuKr22 — APPROVED** [review]
ok

**Pull request merged**
