### PR TITLE
ADD Documentation Template

### LINKED ISSUE #294: ADD Documentation Template
Here are the points for Documentation Update template:

**Is there an existing issue for this?**

I have searched the existing issues (required)

**Issue Description**

Please provide a clear description of the documentation update you are suggesting. (required)

**Suggested Change**

Provide details of the proposed change to the documentation. (required)

**Rationale**

Why is this documentation update necessary or beneficial? (optional)

**Urgency**

How urgently do you believe this documentation update is needed?
High
Medium
Low (required)

**Acknowledgements**

I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md) (required)
I'm a GSSOC'24-Extd contributor
I'm a Hacktoberfest contributor
I have starred the repository (required)
I am willing to work on this issue (optional)

Screenshot 2024-10-27 222615

### PR DESCRIPTION
**Pull request by alo7lika**
## 📋 Description

This pull request enhances the documentation for improved clarity and usability, especially focusing on helping new users set up and navigate the project more effectively.

## 🔨 Changes Made
- Improved formatting and organization in `ISSUE_TEMPLATE`
- Added clearer instructions in the Installation Guide
- Updated Configuration Guide with additional examples and explanations

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [x] Documentation update 📚

## 🤝 Related Issues
- Fixes #294

---

### CODE REVIEW

**Comment by alo7lika** [comment]
@sid0000007 the task has been completed. Kindly review the PR

**Review by AshuKr22 — APPROVED** [review]
thank you

**Comment by alo7lika** [comment]
> thank you

add labels on the PR Kindly

**Comment by alo7lika** [comment]
> > thank you
> 
> add labels on the PR Kindly

@sid0000007  @AshuKr22

**Comment by alo7lika** [comment]
@sid0000007 @AshuKr22  kindly **ADD LABEL ON THE PR "GSSOC-EXT"**

**Comment by alo7lika** [comment]
> @sid0000007 @AshuKr22 kindly **ADD LABEL ON THE PR "GSSOC-EXT"**

@sid0000007

**Pull request merged**
