### PR TITLE
Issue/110 - Add search functionality to my lists page

### PR DESCRIPTION
**Pull request by nidhi2026**
### Description
This pull request introduces a search feature to the Lists page, enabling users to filter and find lists by name as the number of lists increases.

Resolves issue #110 

### Result

https://github.com/user-attachments/assets/7ac9bbfb-1020-4515-81af-f85520a2a41e

### CODE REVIEW

**Comment by nidhi2026** [comment]
@AshuKr22 
Are the changes fine, or should I make some changes

**Comment by nidhi2026** [comment]
@daccotta If my pr is fine, please label it with gssoc-ext and level

**Review by AshuKr22 — APPROVED** [review]
Thank you

**Review by sid0000007 — COMMENTED** [review]
ok

**Pull request merged**
