### PR TITLE
Fix: fixed issue #56 - make send request button responsive

### LINKED ISSUE #56: [FIX-FRONTEND] the send request button is not looking in mobile view
**Description:**  
In the "Friends" section, the **Send Request** button is too large and unresponsive on mobile view. It negatively impacts the user experience, as the button does not scale well with smaller screens. I propose replacing the button's text with an icon to improve responsiveness and maintain a clean UI.

**Acceptance Criteria:**  
- Replace the **Send Request** button text with an "Add Friend" icon, ideally imported from Lucide React or Tabler Icons.  
- The button should be fully responsive and fit seamlessly within the mobile layout without cutting off or misaligning.  
- Ensure consistent styling with the rest of the application components.

**Steps to Reproduce:**  
1. Navigate to the "Friends" section on a mobile device.
2. Search for a user and observe the **Send Request** button's appearance.
3. Notice that the button is oversized and not responsive.

**Proposed Solution:**  
- Replace the current button text with a simple "Add Friend" icon from either Lucide React or Tabler Icons.  
- Adjust button dimensions to ensure it fits within mobile views without overflowing or looking out of place.  
- Ensure that the button remains accessible (i.e., aria-label and appropriate hover/focus states).

**Files Involved:**  
- `Friends` page or any file handling the button design in the Friends UI.

**Difficulty:**  
Beginner

Please refer to the README and CONTRIBUTING guides for more context.

---

### PR DESCRIPTION
**Pull request by Dhruv-pahuja**
## Overview
This PR fixes issue #56 where the 'Send Request' button was not properly styled or responsive on mobile devices.

## Changes
- I replaced the text of the "Send Request" button with an **"Add Friend"** icon from **Lucide React** to improve responsiveness and maintain a cleaner UI on mobile.
- Updated button styles for better responsiveness on smaller screens.
- Added appropriate padding and icon size adjustments for mobile view using Tailwind CSS.
- Ensured the button fits within mobile views without overflowing or looking out of place.
- Added accessibility attributes (aria-label) to improve screen reader support.

## Issue Reference
Fixes #56 

## Screenshots
- Before: 
before

- After: 
after

## Testing Instructions
- i have Checked the button responsiveness on various mobile screen sizes (e.g., iPhone 5/SE, iPhone X, etc.).

### CODE REVIEW

**Review by daccotta — APPROVED** [review]
ok

**Review by sid0000007 — APPROVED** [review]
ok

**Comment by Dhruv-pahuja** [comment]
@sid0000007 @daccotta  can anyone of you  add labels of gssoc-ext and level1 to this PR please as of latest guideliness in official announcements of GSSoC extended editions discord community

**Comment by sid0000007** [comment]
> @sid0000007 @daccotta can anyone of you add labels of gssoc-ext and level1 to this PR please as of latest guideliness in official announcements of GSSoC extended editions discord community

@Dhruv-pahuja Added your mentioned labels.

**Pull request merged**
