### PR TITLE
Revamp crousel to make it more appealing 

### LINKED ISSUE #78: Add Carousel to the Header Section
To enhance the visual appeal of the header section, we need to add a carousel that will rotate through images or content. The carousel should be implemented in a way that fits seamlessly within the existing header layout, providing an engaging experience for users without disrupting the header's functionality.
 
@daccotta  please assign this to me 
Screenshot 2024-10-08 at 2 37 19 AM
i am planning to implement this part header part 

for hero section only

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #78 
Screenshot 2024-10-10 at 1 35 27 AM
@daccotta Please approve my PR

### CODE REVIEW

**Comment by AshuKr22** [comment]
hey @shubhagarwal1 can you also attach a ss of its phone view ? 😅 A recording video would also work fine. 
And can those forwards and previous manuall button be more more bigger and with no background. Like Amazon Prime caresoul 
Screenshot 2024-10-10 at 2 37 20 PM

**Comment by shubhagarwal1** [comment]
> hey @shubhagarwal1 can you also attach a ss of its phone view ? 😅 A recording video would also work fine. And can those forwards and previous manuall button be more more bigger and with no background. Like Amazon Prime caresoul Screenshot 2024-10-10 at 2 37 20 PM

@AshuKr22 okay will make the changes

**Comment by AshuKr22** [comment]
hey @shubhagarwal1  the ss is not visible.

**Comment by shubhagarwal1** [comment]
> hey @shubhagarwal1 the ss is not visible.

i have removed the backgournd from the slide button

**Review by AshuKr22 — APPROVED** [review]
thank you

**Pull request merged**
