### PR TITLE
Enhance and structure the Contributors Section 

### PR DESCRIPTION
**Pull request by alo7lika**
## Description :
The current "Contributors" section in the README lacks structure and visual appeal. Enhancing this section will better recognize contributors and encourage more participation. The goal is to make it more engaging, visually appealing, and organized while highlighting the valuable efforts of everyone involved.

### CODE REVIEW

**Comment by AshuKr22** [comment]
hey @alo7lika can you please attach a screenshot of the contributor section for reference

**Comment by alo7lika** [comment]
> hey @alo7lika can you please attach a screenshot of the contributor section for reference

Screenshot 2024-10-24 215207

**Comment by alo7lika** [comment]
> > hey @alo7lika can you please attach a screenshot of the contributor section for reference
> 
> Screenshot 2024-10-24 215207
> 
> 

@AshuKr22

**Review by AshuKr22 — APPROVED** [review]
thank you

**Pull request merged**
