### PR TITLE
Update Contact Channel in Readme.md

### PR DESCRIPTION
**Pull request by Varunshiyam**
Updated the Readme file by adding up the Contact Section , creating a Warm welcome message at the top , Adding some Visual Emoji than the regular one .

This solves the Issue #232 

**Kindly Assign this to me under Labels :**
gssoc
hacktoberfest

### CODE REVIEW

**Comment by AshuKr22** [comment]
@Varunshiyam can you please attach some visuals of the work you have done

**Comment by Varunshiyam** [comment]
Screenshot 2024-10-24 at 10 36 34 AM


------


https://github.com/user-attachments/assets/15fbe02c-3514-4d13-bdae-3fea6f5b5767


------


These are the changes I wish to do

**Comment by sid0000007** [comment]
@Varunshiyam Looks amazing. Just few request changes. which are following :
1. Remoove the Emoji from daccotta heading (keep it SImple )
2. match the text animation colour to the text colour of daccotta landing page daccotta.com (attached image for your reference)
Screenshot 2024-10-24 at 11 43 07 AM

Ping me up when you complete this.

**Comment by Varunshiyam** [comment]
@sid0000007 . I have Corrected the changes kindly review it 




https://github.com/user-attachments/assets/39c10dbb-a933-4b25-90c5-0d0ff37f3801

**Review by sid0000007 — APPROVED** [review]
ok

**Pull request merged**
