### PR TITLE
Unable to Sign Up with Email Providers Other Than Gmail

### LINKED ISSUE #221: Unable to Sign Up with Email Providers Other Than Gmail
## Description

Users are currently unable to sign up using email providers other than Gmail. Attempting to register with providers such as Yahoo, Outlook, or custom domain emails results in an error or failed sign-up process. This issue is limiting the user base to only Gmail users, which may hinder the growth of the platform.

## Steps to Reproduce

1. Navigate to the sign-up page.
2. Enter an email address from a provider other than Gmail (e.g., Yahoo, Outlook, custom domain).
3. Fill in the required details and submit the form.
4. Observe the error or the failure to proceed with the sign-up process.

## Expected Behavior

Users should be able to sign up using any valid email address, regardless of the provider (e.g., Yahoo, Outlook, custom domains).

image

Please assign this issue to me for Hacktoberfest and GSoC-ext

### PR DESCRIPTION
**Pull request by ghost**
Fixed: #221 

Users are currently unable to sign up using email providers other than Gmail. Attempting to register with providers such as Yahoo, Outlook, or custom domain emails results in an error or failed sign-up process. This issue is limiting the user base to only Gmail users, which may hinder the growth of the platform.

### CODE REVIEW

**Comment by AshuKr22** [comment]
@amitb0ra how are you confirming that the input given by user is actually an email?. you should have implemented either some kind of regex or added checks for other input providers now anyone can input anything in email.

**Review by AshuKr22 — CHANGES_REQUESTED** [review]
add either regex or checks for if the value inputted by the user is actually an email or not.

**Comment by ghost** [comment]
is it okay? https://regexr.com/2rhq7

also, do you want specific route to check email? /check-email?

**Comment by ghost** [comment]
@AshuKr22 is it okay?

**Comment by AshuKr22** [comment]
@amitb0ra yeah its good

**Review by AshuKr22 — APPROVED** [review]
thank you

**Comment by ghost** [comment]
@AshuKr22 You forgot to add GSSoC'24 ext and hacktoberfest labels. Can you add them please

**Comment by ghost** [comment]
@sanjay-kv @AshuKr22 please provide labels in it. ITS IMPORTANT

**Pull request merged**
