### PR TITLE
Added forget password with firebase

### LINKED ISSUE #163: Add "Forgot Password" Interface
The current system lacks a "Forgot Password" feature, preventing users from recovering their accounts if they forget their credentials. We need to design and implement a user-friendly interface that allows users to request a password reset via email, improving the overall user experience and account security.

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
fixes #163

- [x] Remove password validation when clicked on forget password

### CODE REVIEW

**Comment by sid0000007** [comment]
@mehul-m-prajapati can you please share a working video for the feature.

**Comment by mehul-m-prajapati** [comment]
@sid0000007 : There is one pending thing for this: Remove password validation when clicked on forget password

- I will complete it and attach video for same

**Comment by mehul-m-prajapati** [comment]
@sid0000007 : Here is a working video


Animation4
---
p1
p2
p3

**Review by sid0000007 — APPROVED** [review]
ok

**Pull request merged**
