### PR TITLE
Fix Debouce on all buttons 

### LINKED ISSUE #102: Fix all Debouce Bug on the Application
@daccotta please assign me this task

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #102 
https://github.com/user-attachments/assets/d482521d-b6de-42d0-a5f6-bee3c333c246

### CODE REVIEW

**Comment by mehul-m-prajapati** [comment]
@shubhagarwal1 : similar logic to fix friend request pr #142, will create conflict depending on which pr gets merged fist

**Review by sid0000007 — APPROVED** [review]
ok

**Comment by shubhagarwal1** [comment]
@daccotta i have solved the conflicts please merge the PR.

**Comment by mehul-m-prajapati** [comment]
@daccotta : This merge overwrites my previous changes.

**Comment by shubhagarwal1** [comment]
> @daccotta : This merge overwrites my previous changes.

hey @mehul-m-prajapati Your previous changes in the friend request section were same that i did, also there is not diffence in the functionality so dont think that this would lead toany error

**Comment by AshuKr22** [comment]
@shubhagarwal1 i see the override doesnt conflict with the previous changes the overall integration is good , so I am merging the pr. closes #151

**Pull request merged**
