### PR TITLE
added show and hide password

### LINKED ISSUE #59: Adding password show/hide option
I wanted to add password show/hide button in password inputs login, signup
Screenshot 2024-10-04 221616

### PR DESCRIPTION
**Pull request by Sourabh782**
Closes : #59 

Added show hide password functionality

Screenshot 2024-10-05 201118
Screenshot 2024-10-05 201053
Screenshot 2024-10-05 200907

### CODE REVIEW

**Review by AshuKr22 — CHANGES_REQUESTED** [review]
hey the changes seems good , just a small thing can you use  lucide / tabler icons in instead of images from web in show / hide ?

**Comment by Sourabh782** [comment]
@AshuKr22 ya sure doing it

**Comment by sid0000007** [comment]
> @AshuKr22 ya sure doing it

have you done it ?

**Comment by Sourabh782** [comment]
@sid0000007  ya i have done it, will be pushing shortly

**Comment by Sourabh782** [comment]
@sid0000007  kindly verify

**Comment by AshuKr22** [comment]
hey @Sourabh782  , can you make a new commit without the package-lock.json as it is creating conflicts with our current file.

**Comment by Sourabh782** [comment]
sure

**Comment by Sourabh782** [comment]
@AshuKr22 check now?

**Review by sid0000007 — DISMISSED** [review]
ok

**Comment by AshuKr22** [comment]
hey @Sourabh782 , the problem as of now is you deleted the package-lock.json file . it is not a viable solution as if we merge that , our package-lock.json file would also deleted. i suggest a workaround. go to daccotta's dev branch copy the package-lock.json file contents and add them to your lock file. it would eliminate all conflicts.

**Comment by Sourabh782** [comment]
Sure  @AshuKr22

**Comment by Sourabh782** [comment]
@AshuKr22 is it now ok? or i'll start from a fresh pull

**Comment by Sourabh782** [comment]
@AshuKr22 any update

**Comment by AshuKr22** [comment]
hey @Sourabh782 sorry for the late reply . the main package.json looks fine but the client package-json is still missing : 
image

**Comment by Sourabh782** [comment]
Oh really sorry @AshuKr22 doing it now

**Comment by Sourabh782** [comment]
@AshuKr22 check now i have copied current package-lock.json from client folder

**Review by AshuKr22 — APPROVED** [review]
ok

**Pull request merged**
