### PR TITLE
Implemented Sorting Functionality for Journal Entries by Month and Year

### LINKED ISSUE #240: [Feature]: Add Sorting Feature for "My Journal" by Month and Year
### What is the proposed feature?
Add a sorting functionality in the "My Journal" section of the movie-based app that allows users to sort entries according to month and year. This feature will improve the user experience by enabling users to easily organize and view journal entries based on the time they were created or edited.

### Expected Outcome
- Users should be able to select a sorting option that filters the journal entries by month and year.
- The sorting method should dynamically update the displayed entries to reflect the selected time period.

image

Please assign this issue to me under gssoc-ext level3 and hactoberfest-accepted, @sid0000007 , as I am interested in working on it.

### PR DESCRIPTION
**Pull request by PrityanshuSingh**
### 📋 Description

This PR implements a sorting functionality in the "My Journal" section of the movie-based app, allowing users to sort their journal entries by month and year. This feature aims to enhance the user experience by enabling users to easily organize and view their entries based on the time they were created.

### 🔨 Changes Made

- Added a dropdown popover menu for selecting sorting options (month and year).
- Implemented logic to filter and display journal entries based on the selected time period.
- Updated the UI to dynamically reflect the sorting criteria applied.
- Ensured that sorting updates the displayed entries without requiring a page refresh.

Fixes #240 

### ✅ Checklist

- [x] I have followed all the guidelines mentioned in `CONTRIBUTING.md`.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have tested it locally and it works fine.

### 🏷️ Types of Changes

- [x] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨

### 📸 Screenshots/Videos (if applicable)

https://github.com/user-attachments/assets/1d4790be-2218-478d-803d-e38374e098c8

This video shows the new sorting options added in the "My Journal" section.

@sid0000007, please consider assigning me the labels gssoc-ext level3 and hacktoberfest-accepted for this new feature once the PR is merged.

### CODE REVIEW

**Comment by sid0000007** [comment]
@PrityanshuSingh Please change the button content to filter by month to only filter. and then Let us know

**Comment by PrityanshuSingh** [comment]
> @PrityanshuSingh Please change the button content to filter by month to only filter. and then Let us know

Ok will change it accordingly.

**Comment by sid0000007** [comment]
> > @PrityanshuSingh Please change the button content to filter by month to only filter. and then Let us know
> 
> Ok will change it accordingly.

what's the status ? you have to just change the text to 'filter'.

**Comment by PrityanshuSingh** [comment]
> > > @PrityanshuSingh Please change the button content to filter by month to only filter. and then Let us know
> > 
> > 
> > Ok will change it accordingly.
> 
> what's the status ? you have to just change the text to 'filter'.

was a bit busy yesterday, just changed it to filter, kindly review once.

**Comment by PrityanshuSingh** [comment]
@sid0000007, kindly consider assigning me label of level3 once the PR gets merged, as i have implemented a new sorting feature for journal.

**Comment by PrityanshuSingh** [comment]
@sid0000007 kindly review the PR and inform me about any further changes required.

**Review by sid0000007 — APPROVED** [review]

**Pull request merged**
