### PR TITLE
Feat: Adding CI-CD Workflow

### LINKED ISSUE #199: Setup CICD with netlify Preview Deployment of every active the PR
Setup CICD with netlify Preview Deployment of every active the PRDeployment Preview of Netlify Build Not Visible in Pull Requests

Issue Description:

We are currently facing an issue where the deployment preview from Netlify is not visible in the pull requests for the Daccotta repository. This is crucial to ensure the seamless deployment and testing of changes before they are merged.

Task:

We are looking for contributors to:

	•	Implement a CI/CD workflow in the GitHub Actions that ensures Netlify previews are correctly generated for each PR.
	•	Ensure that the deployment previews are workable and deployable, allowing reviewers to check the live version of
                 changes before merging.

1. If you’re new to the project, please follow the setup instructions available in the [README] and refer to our [CONTRIBUTING.md] for detailed contribution guidelines.
2. For any questions, discussions, or support, feel free to join our [Discord community](https://discord-link/) and connect with fellow contributors.

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #199 Adding CICD Workflow with netlify Preview Deployment of every active the PR.
Now for creating every PR first it will check is your code deploy successful or not and also pass some testcase.

@sid0000007 Please review it and merge it:)

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@sid0000007 ???????

**Review by sid0000007 — APPROVED** [review]

**Comment by harshbhar0629** [comment]
@sid0000007 Please assign the level-3 and gssoc-ext.

**Comment by harshbhar0629** [comment]
My gssoc socre is not increased by this merged so please assign the label @sid0000007 Please bro:)

**Comment by harshbhar0629** [comment]
@sid0000007 Please assign the label:)

**Comment by harshbhar0629** [comment]
@sid0000007 Please assign the level-3....???????

**Comment by harshbhar0629** [comment]
@sid0000007 You successfully merge my PR but not assigned the level-3 why??

**Comment by harshbhar0629** [comment]
@sid0000007 Please assign the label i put alot of effort for creating this template:)

**Comment by harshbhar0629** [comment]
@sid0000007 please assign the label:)

**Comment by harshbhar0629** [comment]
@sid0000007 Is there any problem to assign the label

**Comment by shreya-paul-17** [comment]
@sanjay-kv @MastanSayyad please review it

**Review by MastanSayyad — COMMENTED** [review]
Hi @harshbhar0629 workflows can only have level 1 as per the given guidelines
reducing it from level 2 to level 1

**Pull request merged**
